version: '3.1'

services:
  telegram-bot:
    depends_on:
      - bot_db
    build:
      context: .
    environment:
      - BOT_NAME=${BOT_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_DB_USERNAME=${BOT_DB_USERNAME}
      - BOT_DB_PASSWORD=${BOT_DB_PASSWORD}
    restart: always
  bot_db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${BOT_DB_USERNAME}
      - POSTGRES_PASSWORD=${BOT_DB_PASSWORD}
      - POSTGRES_DB="telegram_bot_db"
      - POSTGRES_ROOT_PASSWORD="postgres"
    ports:
      - "3306:3306"
    expose:
      - "3306"