spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_bot_db
    password: postgres
    username: postgres
  flyway:
    baseline-on-migrate: true
    locations: filesystem:\Users\MTikhonenko\IdeaProjects\telegram-bot\src\main\resources\db.migration
  sql:
    init:
      mode: always